const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_STADIUM: 'GET_STADIUM',
    GET_STADIUMS_BY_SELECT: 'GET_STADIUMS_BY_SELECT',
    GET_STADIUMS_BY_SEARCH: 'GET_STADIUMS_BY_SEARCH',
    CATCH_STADIUMS_SEARCH: 'CATCH_STADIUMS_SEARCH',
    CLEAR_STADIUMS_STATE: 'CLEAR_STADIUMS_STATE',

}

export default ACTIONS;